--CREATE TRIGGER UTG_UPDATEBILLINFO
--ON PDT_BILLINFO FOR INSERT, UPDATE
--AS
--BEGIN
--	DECLARE @IDBILL INT
--	SELECT @IDBILL=idBill FROM INSERTED
--	DECLARE @IDTABLE INT
--	SELECT @IDTABLE=idTable FROM PDT_BILL WHERE idBill=@IDBILL AND status =-1
--	UPDATE PDT_TABLE SET tableStatus=1 WHERE idTable=@IDTABLE
--END
--GO
-------------------
CREATE TRIGGER UTG_UPDATEBILL
ON PDT_BILL FOR INSERT,DELETE
AS
BEGIN
	DECLARE @IDTABLE INT
	SELECT @IDTABLE=idTable FROM INSERTED
	UPDATE PDT_TABLE SET tableStatus=1 WHERE idTable=@IDTABLE
END
GO
--------------------
CREATE TRIGGER UTG_UPDATEBILLDELETE
ON PDT_BILL FOR DELETE
AS
BEGIN
	DECLARE @IDTABLE INT
	SELECT @IDTABLE=idTable FROM DELETED
	UPDATE PDT_TABLE SET tableStatus=-1 WHERE idTable=@IDTABLE
END
GO