CREATE DATABASE QL_COFFEE_CS414BIS_PDT
GO

--Group
--NguyenVanPhuc/LamTranQuocDat/QuocTrung
--Create date 28/01/2018
--DESIGN BY NGUYENVANPHUC

--ACCOUNT
--LOAIDICHVU
--DICHVU
--BAN
--KHUVUC
--BILL
--BILLINFO


USE QL_COFFEE_CS414BIS_PDT
GO

CREATE TABLE PDT_ACCOUNT
(
	id INT IDENTITY PRIMARY KEY,
	useName NCHAR(16) NOT NULL,
	passWork NCHAR(12) NOT NULL,
	sex int DEFAULT 0,--0:NAM;1:NU
	permission int DEFAULT -1,-- -1:STAFF,0:ADMIN
	describeAccount NVARCHAR(MAX) DEFAULT 'ĐÂY LÀ MÔ TẢ OR GHI CHÚ'
)
GO

CREATE TABLE PDT_CATEGORYFOOD
(
	id INT IDENTITY PRIMARY KEY,
	categoryName NVARCHAR(50 )NOT NULL,
	describeCategoryFood NVARCHAR(MAX) DEFAULT 'ĐÂY LÀ MÔ TẢ OR GHI CHÚ'
)
GO

CREATE TABLE PDT_FOOD
(
	id INT IDENTITY PRIMARY KEY,
	FoodName NVARCHAR(50) NOT NULL,
	donViTinh NVARCHAR(20) NOT NULL,
	gia FLOAT NOT NULL,
	describeFood NVARCHAR(MAX) DEFAULT 'ĐÂY LÀ MÔ TẢ OR GHI CHÚ',
	
	idCategoryFood INT NOT NULL,

	FOREIGN KEY (idCategoryFood) REFERENCES PDT_CATEGORYFOOD(id)

)

CREATE TABLE PDT_KHUVUC
(
	id INT IDENTITY PRIMARY KEY,
	khuvucName NVARCHAR(50) NOT NULL,
	describeKhuVuc NVARCHAR(MAX) DEFAULT 'ĐÂY LÀ MÔ TẢ OR GHI CHÚ'
)
GO

CREATE TABLE PDT_TABLE
(
	id INT IDENTITY PRIMARY KEY,
	tableName NVARCHAR(50) NOT NULL,
	tableStatus NVARCHAR(50) NOT NULL DEFAULT 'Bàn trống ',
	describeTable NVARCHAR(MAX) DEFAULT 'ĐÂY LÀ MÔ TẢ OR GHI CHÚ',

	idKhuVuc INT NOT NULL,

	FOREIGN KEY (idKhuVuc) REFERENCES PDT_KHUVUC(id)
)
GO


CREATE TABLE PDT_Bill
(
	id INT IDENTITY PRIMARY KEY,
	billDataCheckIn DATE NOT NULL,
	billDateCheckOut DATE,
	billNameAccount NVARCHAR DEFAULT 'NULL',	
	status INT NOT NULL ,--1: da thanh toan, 0 chua thanh toan
	billTotal FLOAT DEFAULT 0,

	idTable INT NOT NULL,

	FOREIGN KEY (idTable) REFERENCES PDT_TABLE(id)
)
GO

CREATE TABLE PDT_BillInfo
(
	id INT IDENTITY PRIMARY KEY,
	billInfoCount int NOT NULL DEFAULT 0,

	idBill INT NOT NULL,
	idFood INT NOT NULL,

	FOREIGN KEY (idBill) REFERENCES PDT_Bill(id),
	FOREIGN KEY (idFood) REFERENCES PDT_FOOD(id)
	
)
GO
