CREATE DATABASE QL_COFFEE_CS414BIS_PDT
GO

--Group
--NguyenVanPhuc/LamTranQuocDat/QuocTrung
--Create date 28/01/2018
--DESIGN BY NGUYENVANPHUC

--ACCOUNT
--LOAIDICHVU
--DICHVU
--BAN
--KHUVUC
--BILL
--BILLINFO


USE QL_COFFEE_CS414BIS_PDT
GO

CREATE TABLE PDT_ACCOUNT
(
	idAccount INT IDENTITY PRIMARY KEY,
	useName NCHAR(16) NOT NULL,
	passWork NCHAR(12) NOT NULL,
	sex int DEFAULT 0,--0:NAM;1:NU
	permission int DEFAULT -1,-- -1:STAFF,0:ADMIN
	describeAccount NVARCHAR(MAX) DEFAULT N'ĐÂY LÀ MÔ TẢ OR GHI CHÚ'
)
GO

CREATE TABLE PDT_CATEGORYFOOD
(
	idCategory INT IDENTITY PRIMARY KEY,
	categoryName NVARCHAR(50 )NOT NULL,
	describeCategoryFood NVARCHAR(MAX) DEFAULT N'ĐÂY LÀ MÔ TẢ OR GHI CHÚ'
)
GO

CREATE TABLE PDT_FOOD
(
	idFood INT IDENTITY PRIMARY KEY,
	foodName NVARCHAR(50) NOT NULL,
	donViTinh NVARCHAR(20) NOT NULL,
	gia FLOAT NOT NULL,
	describeFood NVARCHAR(MAX) DEFAULT N'ĐÂY LÀ MÔ TẢ OR GHI CHÚ',
	
	idCategoryFood INT NOT NULL,

	FOREIGN KEY (idCategoryFood) REFERENCES PDT_CATEGORYFOOD(idCategory)

)

CREATE TABLE PDT_KHUVUC
(
	idKhuVuc INT IDENTITY PRIMARY KEY,
	khuVucName NVARCHAR(50) NOT NULL,
	describeKhuVuc NVARCHAR(MAX) DEFAULT N'ĐÂY LÀ MÔ TẢ OR GHI CHÚ'
)
GO

CREATE TABLE PDT_TABLE
(
	idTable INT IDENTITY PRIMARY KEY,
	tableName NVARCHAR(50) NOT NULL,
	tableStatus INT NOT NULL DEFAULT -1,
	describeTable NVARCHAR(MAX) DEFAULT 'ĐÂY LÀ MÔ TẢ OR GHI CHÚ',

	idKhuVuc INT NOT NULL,

	FOREIGN KEY (idKhuVuc) REFERENCES PDT_KHUVUC(idKhuVuc)
)
GO


CREATE TABLE PDT_BILL
(
	idBill INT IDENTITY PRIMARY KEY,
	billDataCheckIn DATE NOT NULL,
	billDateCheckOut DATE,
	billNameAccount NVARCHAR DEFAULT 'NULL',	
	billStatus INT NOT NULL ,--1: da thanh toan, 0 chua thanh toan
	billTotal FLOAT DEFAULT 0,

	idTable INT NOT NULL,

	FOREIGN KEY (idTable) REFERENCES PDT_TABLE(idTable)
)
GO

CREATE TABLE PDT_BILLINFO
(
	idBillInfo INT IDENTITY PRIMARY KEY,
	billInfoCount int NOT NULL DEFAULT 0,

	idBill INT NOT NULL,
	idFood INT NOT NULL,

	FOREIGN KEY (idBill) REFERENCES PDT_Bill(idBill),
	FOREIGN KEY (idFood) REFERENCES PDT_FOOD(idFood)	
)
GO
